'''
Given two strings s and t which consist of only lowercase letters.

String t is generated by random shuffling string s and then add one more letter at a random position.

Find the letter that was added in t.

Example:

Input:
s = "abcd"
t = "abcde"

Output:
e

Explanation:
'e' is the letter that was added.
'''

class Solution:
    def findTheDifference(self, s, t):
        """
        :type s: str
        :type t: str
        :rtype: str
        """
        list_s = list(s)
        list_s.sort()
        list_t = list(t)
        list_t.sort()
        for i, v in enumerate(list_s):
            if v != list_t[i]:
                return list_t[i]
        return list_t[-1]